### ISSUE TITLE
link build error

### ISSUE THREAD

**Issue by fsoullier** [AlexSSD7/linsk#15] opened 2024-05-13 22:06 UTC
Hi, 

When running linsk build, the qemu installation seems to encounter a network issue and is not able to reach the Alpine servers. 

`level=ERROR msg="Failed to set up Alpine Linux" caller=storage subcaller=imgbuilder error="run setup cmd (log: 'udhcpc: started, v1.36.1\\nudhcpc: broadcasting discover\\nudhcpc: broadcasting select for 10.0.2.15, server 10.0.2.2\\nudhcpc: lease of 10.0.2.15 obtained from 10.0.2.2, lease time 86400\\nwget: bad address 'mirrors.alpinelinux.org'\\nWarning! No mirror found'): Process exited with status 1"
`
A quick googling led me to this [post](https://stackoverflow.com/questions/76242337/dns-server-issue-in-alpine-guest-when-using-qemu-system-aarch64-on-android-host) mentioning an issue with busybox overwriting resolv.conf.

I am not sure this is the same issue, in any case, a fix would be great. Happy to provide more information if needed. 

Thanks!

**Comment by AlexSSD7** [comment] 2024-05-13 22:16
Duplicate of https://github.com/AlexSSD7/linsk/issues/1.

One of your DNS servers is not responding. Try changing your DNS server configuration to `8.8.8.8` and `8.8.4.4`.

Closing for now. You are free to reopen if the provided solution does not work.

**Closed by AlexSSD7** 2024-05-13 22:16 UTC

**Comment by fsoullier** [comment] 2024-05-13 22:24
Issue fixed as reported on [#1 ]. Thanks for the pointer, apologies for not checking that one.
